version: "3.7"
services:
  postgres:
    image: postgres:11
    container_name: taskdb
    hostname: postgres
    restart: always
    environment:
      - POSTGRES_USER=task
      - POSTGRES_PASSWORD=task
      - POSTGRES_DB=task
    ports:
      - 5432:5432
  myfirstspring:
    image: task-management-system:1.0.0
    container_name: task-management-system
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8180:8180
    environment:
      - spring.datasource.url=jdbc:postgresql://localhost:5432/task