server:
  port: 8180
  error:
    include-message: always
    include-stacktrace: on_param
    include-binding-errors: always
jwt:
  secret: 2413fb3709b05939f04cf2e92f7d0897fc2596f9ad0b8a9ea855c7bfebaae892
  lifetime: 180m
spring:
  application:
    name: task-management-system
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/task
    username: task
    password: task
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-test-query: select 1
      minimum-idle: 5
      maximum-pool-size: 50
      data-source-properties:
        currentSchema: task
      auto-commit: false
  flyway:
    enabled: false
  liquibase:
    change-log: classpath:db.changelog/db.changelog-core.xml
  sql:
    init:
      mode: always