spring:
  application:
    name: task-management-system
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/
    username:
    password:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-test-query: select 1
      minimum-idle: 5
      maximum-pool-size: 50
      data-source-properties:
        currentSchema:
      auto-commit: false
  flyway:
    enabled: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-core.xml
  sql:
    init:
      mode: always